---
title: "DATA"
output: html_document
---

#### Data Describing Netflix Movies and TV Shows  
To explore characteristics of Movies and TV shows available on Netflix, we find a open source data set on [Kaggle](https://www.kaggle.com/datasets/shivamb/netflix-shows?resource=download). This tabular data set concludes listings of all the movies and TV shows available on Netflix and  corresponding details such as - available country, cast, directors, ratings, release year, date added, etc.  
This data set has 8807 unique rows and 12 columns, but it is not presented in a tidy form. One single cell contains several elements. For example, one movie could have several directors and lots of casts. To make the data ready for further analysis, we store elements in a list that we can unnest the variable we interested in as we need. Data wrangling was performed as needed.     



#### World Map Data  
To visualize the information, such as the number of TV Shows and Movies in different countries, in global map, we obtained the geographic information from the data set **world** by accessing the R package **sf**.  
This data set contains world map data from [Natural Earth](https://www.naturalearthdata.com/) with a few variables from [the World Bank](https://data.worldbank.org/), the names of countries and continents. We used the function **left_join** to merge the **Netflix data set** with the **World data set** by country name.   


