---
title: "Global Mapping"
author: "Xiao Ma"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
---

```{r setup, include = FALSE, echo = FALSE}
library(tidyverse)
library(spData)
library(sf)
library(tidyverse)
library(lubridate)
library(gt)
library(paletteer)
library(ggridges)
library(plotly)
library(gtExtras)
library(ggmap)
library(tidycensus)
library(leaflet)
library(osmdata)
library(tigris)
library(ggsflabel)
library(ggthemes)
library(ggplot2)
#Working directory for .RMD
#knitr::opts_knit$set(echo = TRUE,root.dir = rprojroot::find_rstudio_root_file())

#Controlling figure output in markdown
knitr::opts_chunk$set(
#  fig.height =   
  fig.width = 6,
#  fig.asp = .5,
  out.width = "90%",
#  out.height = 
 fig.align  = "center",
  cache = FALSE,
  eval  = TRUE,
  echo  = FALSE,
  warning = FALSE
)

#My Colours (from viridis)
my_purple <- "#440154FF"
my_yellow <- "#FDE725FF"

#Set Theme for ggplot2
theme_set(theme_bw() + theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom"))

#Set Scientific notation output and decimal places for knitr
options(scipen = 999)
options(digits = 4)
options(dplyr.summarise.inform = FALSE)
```


```{r data_read, include = FALSE}
netflix_bak <- read.csv("~/Downloads/netflix_titles.csv", stringsAsFactors=TRUE, na = "")
netflix1 <- netflix_bak %>%
  filter(!is.na(country)) %>%
  separate(col = country,
           sep = ", ",
           into = c("country1","country2","country3","country4","country5","country6","country7","country8","country9","country10","country11","country12")) %>%
  pivot_longer(cols = starts_with("country"), values_to = "country") %>%
  filter(!is.na(country)) 
netflix1$country<-gsub(",", "",netflix1$country) #delete the comma remained
netflix1$country <- ifelse(netflix1$country == "Hong Kong", "China",netflix1$country)
netflix1$country <- ifelse(netflix1$country == "South Korea", "Republic of Korea", netflix1$country)
netflix1$country <- ifelse(netflix1$country == "West Germany", "Germany", netflix1$country)
netflix1$country <- ifelse(netflix1$country == "East Germany", "Germany", netflix1$country)
netflix1$country <- ifelse(netflix1$country == "Russia", "Russian Federation", netflix1$country)
netflix1$country <- ifelse(netflix1$country == "Soviet Union", "Russian Federation",netflix1$country)

netflix_count <- netflix1  %>%
  filter(country!="") %>%
  group_by(country,type) %>%
  summarise(n=n()) %>%
  pivot_wider(names_from = type,values_from = n)
data(world)
map_plotly.df <- world %>%
  left_join(netflix_count, by= c("name_long"="country")) %>%
  mutate(movie_label = str_c(name_long,
                  "\n  Movie: ",
                  Movie),
         tv_label = str_c(name_long,
                  "\n  TV Show: ",
                  `TV Show`))
```

Row {data-height=400}
-----------------------------------------------------------------------

### Numbers of Movie in the world

```{r}
#Generate the ggplot
#plot for movie
movie.gg <- ggplot() +
  geom_sf(data = map_plotly.df, aes(fill = log(Movie), text=movie_label)) +
  labs(title = "Numbers of Movie in the world") +
  scale_fill_viridis_c("log Movie", option="plasma",direction = -1, alpha = 0.8) +
  ggthemes::theme_map()

movie.ggplotly<-ggplotly(movie.gg, tooltip = "text", height =500 ,width = 500 ) %>%
  style(hoveron = "fills")
movie.ggplotly
```

-----------------------------------------------------------------------

### Numbers of TV Show in the world

```{r}
#plot for TV Show
tv.gg <-ggplot() + 
  geom_sf(data = map_plotly.df, aes(fill = log(`TV Show`), text=tv_label)) +
  labs(title = "Numbers of TV Show in the world") +
  scale_fill_viridis_c("log TV Show", option="plasma", alpha = 0.8) +
  ggthemes::theme_map()
tv.ggplotly <-ggplotly(tv.gg, tooltip = "text", height =500 ,width =500) %>%
  style(hoveron = "fills")
tv.ggplotly
```

Row {data-height=600}
-----------------------------------------------------------------------
### Numbers of TV Shows and movies in different continents
```{r}
continent.gg <- netflix1 %>%
  filter(release_year %in% 2021:2011) %>%
  left_join(world %>% select(name_long,continent),
            by= c("country"="name_long"))  %>%
  group_by(type,release_year,continent)%>%
  summarise(n=n())%>%
  filter(!is.na(continent)) %>%
  mutate(text_label = str_c(n, " ",type," produced in ",continent," in ",release_year)) %>%
  ggplot(aes(x=release_year,y=n,fill=type, text = text_label)) +
           geom_bar(stat = "identity",position = "dodge") +
  facet_wrap(~continent, scales = "free")+
  labs(title = "Numbers of TV Shows and movies in different continents",
       subtitle = "In recent ten years",
    x     = "Release year",
    y     = "Number")+theme_light()

#ggplotly() + tooltip to control label
continent.ggplotly <-ggplotly(continent.gg, tooltip = "text") #tooltip controls text hover/labelx
continent.ggplotly
```
